### ISSUE TITLE
モデル作る

### ISSUE THREAD

**Issue by nobuyo** [13J-Programmers/gourmet#2]
### order

- has_many `menu`

|カラム名|型|中身|
|:--:|:--:|:--:|
|id|integer|主キー|
|status|integer|orderの状態|

### menu

|カラム名|型|中身|
|:--:|:--:|:--:|
|id|integer|主キー|
|name|string|商品名|
|amount|integer|金額|
|stock|integer|在庫|
|with_cheese|bool|トッピングチーズ|

**Comment by tex2e** [comment]
以前 #7 で amount（量）は sold_amount （売れた量）にした方がいいと言いましたが、ここを見るとニュアンスが違かったようです。
金額は cost か price の方が適切です。

**Comment by nobuyo** [comment]
ああ、何も考えてなかった、`price`がぴったりですね(#4で一緒に修正します)
